spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Na260206
    username: postgres
    url: jdbc:postgresql://localhost:5432/micro
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true